# Generated by Django 5.2.7 on 2025-11-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='メモ')),
                ('location', models.CharField(max_length=255, verbose_name='場所')),
                ('date', models.DateTimeField(verbose_name='時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール',
                'db_table': 'schedules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='schedules_user_id_b35612_idx')],
            },
        ),
    ]
