import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        {/* ダークモード設定を即座に適用するスクリプト */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  let darkMode = localStorage.getItem('darkMode') === 'true';
                  let root = document.documentElement;
                  if (darkMode) {
                    root.style.setProperty('background-color', '#1f2937', 'important');
                  } else {
                    root.style.setProperty('background-color', '#ffffff', 'important');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}