# Generated by Django 5.2.7 on 2025-11-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('iconImage', models.CharField(max_length=255, verbose_name='アイコン画像')),
                ('color', models.CharField(max_length=255, verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ブックマーク',
                'verbose_name_plural': 'ブックマーク',
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
