# Generated by Django 5.2.7 on 2025-11-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('iconEmoji', models.CharField(max_length=255, verbose_name='アイコン絵文字')),
                ('color', models.CharField(max_length=255, verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ブックマーク',
                'verbose_name_plural': 'ブックマーク',
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bookmarks_user_id_6c0ac9_idx')],
            },
        ),
    ]
