# Generated by Django 5.2.7 on 2025-11-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='iconImage',
            new_name='iconEmoji',
        ),
    ]
