# Generated by Django 5.2.7 on 2025-11-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(db_index=True, help_text='GoogleのユーザーID(sub)。メールアドレスが変わっても不変', max_length=255, unique=True, verbose_name='Google User ID')),
                ('picture_url', models.URLField(blank=True, help_text='Googleプロフィール画像のURL', verbose_name='プロフィール画像URL')),
                ('locale', models.CharField(blank=True, default='ja', help_text='ユーザーの言語設定(例：ja, en)', max_length=10, verbose_name='言語設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
